# -*- coding: utf-8 -*-
"""p1.2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gZ8Ehdi1Npgr3O-wV7Z41WNojhzpFlNy
"""

def programa(n, filas):

    # creamos M
    M = []

    # inicializamos M
    for i in range(n):
        fila = [0] * n
        M.append(fila) # asumo que podemos ocupar esto

    # copiamos los valores de las filas en la matriz M
    for i in range(n):
        for j in range(n):
            M[i][j] = filas[i][j]

    

    # clausura reflexiva
    for i in range(n):
        M[i][i] = 1
    


    
    #clausura transitiva
    contador = 0
    while True:
     for i in range(n):
        for j in range(n):
            for k in range(n):
                if M[i][j] == 1 and M[j][k] == 1:
                  if M[i][k]==0:
                    contador+=1
                  M[i][k]=1
                    
                    
     
     if contador == 0:
      break
    
     contador = 0

    # clausura simétrica
    for i in range(n):
        for j in range(n):
            if M[i][j] == 1:
                M[j][i] = 1
    
    
    
    

    # retornamos M prima (nueva)
    return M

# entrada y salida
n = 4
filas =  [[1, 0, 1, 0], [1, 0, 1, 1], [1, 1, 0, 0], [1, 0, 0, 0]]
matriz = [[1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1]]
programa(n, filas) 

assert programa(n,filas)==matriz

# ／l、
# （ﾟ､ ｡７
# l、ﾞ~ヽ
# じしf_, )ノ un gato